# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: todo.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'todo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntodo.proto\x12\x04todo\"7\n\x11TodoCreateRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"U\n\x10TodoItemResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x11\n\tcompleted\x18\x04 \x01(\x08\"9\n\x10TodoListResponse\x12%\n\x05todos\x18\x01 \x03(\x0b\x32\x16.todo.TodoItemResponse\"\x07\n\x05\x45mpty2}\n\x0bTodoService\x12=\n\nCreateTodo\x12\x17.todo.TodoCreateRequest\x1a\x16.todo.TodoItemResponse\x12/\n\x08GetTodos\x12\x0b.todo.Empty\x1a\x16.todo.TodoListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TODOCREATEREQUEST']._serialized_start=20
  _globals['_TODOCREATEREQUEST']._serialized_end=75
  _globals['_TODOITEMRESPONSE']._serialized_start=77
  _globals['_TODOITEMRESPONSE']._serialized_end=162
  _globals['_TODOLISTRESPONSE']._serialized_start=164
  _globals['_TODOLISTRESPONSE']._serialized_end=221
  _globals['_EMPTY']._serialized_start=223
  _globals['_EMPTY']._serialized_end=230
  _globals['_TODOSERVICE']._serialized_start=232
  _globals['_TODOSERVICE']._serialized_end=357
# @@protoc_insertion_point(module_scope)
