# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: todo.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import todo_pb2


class TodoServiceBase(abc.ABC):

    @abc.abstractmethod
    async def CreateTodo(self, stream: 'grpclib.server.Stream[todo_pb2.TodoCreateRequest, todo_pb2.TodoItemResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetTodos(self, stream: 'grpclib.server.Stream[todo_pb2.Empty, todo_pb2.TodoListResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/todo.TodoService/CreateTodo': grpclib.const.Handler(
                self.CreateTodo,
                grpclib.const.Cardinality.UNARY_UNARY,
                todo_pb2.TodoCreateRequest,
                todo_pb2.TodoItemResponse,
            ),
            '/todo.TodoService/GetTodos': grpclib.const.Handler(
                self.GetTodos,
                grpclib.const.Cardinality.UNARY_UNARY,
                todo_pb2.Empty,
                todo_pb2.TodoListResponse,
            ),
        }


class TodoServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.CreateTodo = grpclib.client.UnaryUnaryMethod(
            channel,
            '/todo.TodoService/CreateTodo',
            todo_pb2.TodoCreateRequest,
            todo_pb2.TodoItemResponse,
        )
        self.GetTodos = grpclib.client.UnaryUnaryMethod(
            channel,
            '/todo.TodoService/GetTodos',
            todo_pb2.Empty,
            todo_pb2.TodoListResponse,
        )
